env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://urban-engine-gw6rv6jr4qxfv6jp-8080.app.github.dev/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://urban-engine-gw6rv6jr4qxfv6jp-8080.app.github.dev/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap_report.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
