name: Automated SAST with Semgrep

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  security-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semrep CI
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"